In [1]:
import numpy as np
from scipy import linalg

digitalInput = 154

#Set base resistor value
R = 1200

# Set number of digital bits (Resolution)
res = 8

r2r = np.zeros((res,res))

for i in range(0,res-1):
    r2r.itemset((i, i), -5 * R)
    r2r.itemset((i, i+1), 2 * R)
    r2r.itemset((i+1, i), 2 * R)
r2r.itemset((res - 1, res - 1), -4 * R)

r2r = np.matrix(r2r)
np.set_printoptions(linewidth=120) # Prevent line wrapping on a 16x16 matrix
print(r2r)
print(r2r.item((res-1, res-1))) #test read element from matrix


[[-6000.  2400.     0.     0.     0.     0.     0.     0.]
 [ 2400. -6000.  2400.     0.     0.     0.     0.     0.]
 [    0.  2400. -6000.  2400.     0.     0.     0.     0.]
 [    0.     0.  2400. -6000.  2400.     0.     0.     0.]
 [    0.     0.     0.  2400. -6000.  2400.     0.     0.]
 [    0.     0.     0.     0.  2400. -6000.  2400.     0.]
 [    0.     0.     0.     0.     0.  2400. -6000.  2400.]
 [    0.     0.     0.     0.     0.     0.  2400. -4800.]]
-4800.0
